# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: latest
          run_install: false

      -  uses: actions/setup-node@v2
         with:
           node-version: '14'
           cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Set Git creds
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      # Runs a single command using the runners shell
      - name: ng deploy
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: pnpm exec ng deploy --base-href=/ng-mapper-bench/ --no-silent
